/**
 * saveArtifactStateFn's handler body is written inline inside `.handler(...)` (see
 * artifacts.ts:22-32) and, unlike a plain function, can't be imported and called directly in a unit
 * test: calling the exported const outside the real server runtime throws "No Start context found
 * in AsyncLocalStorage" (see session-middleware.unit.test.ts's note) - the framework only executes
 * the real handler body when a request reaches it through TanStack Start's compiled server-fn RPC
 * route, which is generated by the `tanstackStart()` Vite plugin and isn't wired into
 * vitest.config.ts.
 *
 * This suite drives that real route for real via testing/server.ts, which boots Vite's own dev
 * server (the same request-handling stack `pnpm dev` runs) as an in-process test harness instead of
 * a spawned child process + TCP port - see that file's comment for exactly how, and for the
 * internal-API risk it accepts (a TanStack Start or Vite upgrade could break this loudly; that's
 * judged an acceptable trade for actually exercising saveArtifactStateFn's 64 KB cap and not-found
 * guard, the entire point of this file, rather than a test that can't fail when that logic breaks).
 */
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { bootTestServer, serverFnCaller, signInOwner } from '@testing/server';
import type { ServerFnCaller, TestServer } from '@testing/server';

const dbDir = mkdtempSync(join(tmpdir(), 'exhibit-artifacts-int-'));
const dbFile = join(dbDir, 'app.db');

process.env.DATABASE_PATH = dbFile;
/**
 * TanStack Start's compiled client stub reads this to build the RPC URL; the app itself never sets
 * it directly (Vite's `define` config normally inlines it at build time), so we own it here - see
 * test-server.ts.
 */
process.env.TSS_SERVER_FN_BASE = '/_serverFn/';

const ORIGIN = 'http://localhost:3000';
const OWNER_EMAIL = 'owner@example.com';
const OWNER_PASSWORD = 'correct horse battery staple';

let server: TestServer;
let artifactId: string;
let ownerCookie: string;
let saveArtifactState: ServerFnCaller;
let getArtifactDetail: ServerFnCaller;
let updateArtifactMetadata: ServerFnCaller;

beforeAll(async () => {
  const { createArtifact } = await import('@/database/repository');
  const { db } = await import('@/database');
  const { seedOwner } = await import('@/lib/seed');

  await seedOwner(OWNER_EMAIL, OWNER_PASSWORD);

  const { artifact } = createArtifact(db, {
    title: 'Fixture',
    type: 'spec',
    body: JSON.stringify({
      root: 'a',
      elements: { a: { type: 'Prose', props: {}, children: [] } },
    }),
  });

  artifactId = artifact.id;

  server = await bootTestServer(new URL('../../vite.config.ts', import.meta.url));
  ownerCookie = await signInOwner(server, ORIGIN, OWNER_EMAIL, OWNER_PASSWORD);
  saveArtifactState = await serverFnCaller(
    server,
    '/src/lib/artifacts.ts',
    'saveArtifactStateFn',
    'POST',
    ORIGIN,
  );
  getArtifactDetail = await serverFnCaller(
    server,
    '/src/lib/artifacts.ts',
    'getArtifactDetailFn',
    'GET',
    ORIGIN,
  );
  updateArtifactMetadata = await serverFnCaller(
    server,
    '/src/lib/artifacts.ts',
    'updateArtifactMetadataFn',
    'POST',
    ORIGIN,
  );
}, 30000);

afterAll(async () => {
  await server.vite.close();
  rmSync(dbDir, { recursive: true, force: true });
});

describe('saveArtifactStateFn (through the real server-fn RPC route)', () => {
  it('persists state for a real, authenticated caller and it round-trips through getArtifactDetailFn', async () => {
    const saveResult = await saveArtifactState(
      { id: artifactId, state: { checked: true } },
      { cookie: ownerCookie },
    );

    expect(saveResult).toEqual({ saved: true });

    const detail = (await getArtifactDetail({ id: artifactId }, { cookie: ownerCookie })) as {
      state: unknown;
    };

    expect(detail.state).toEqual({ checked: true });
  });

  it('rejects a state payload over the 64 KB cap', async () => {
    await expect(
      saveArtifactState(
        { id: artifactId, state: { big: 'x'.repeat(70_000) } },
        { cookie: ownerCookie },
      ),
    ).rejects.toThrow('Interaction state exceeds the 64 KB limit.');
  });

  it('rejects an unknown artifact id', async () => {
    await expect(
      saveArtifactState({ id: 'nonexistent-id', state: {} }, { cookie: ownerCookie }),
    ).rejects.toThrow('Artifact not found. It may have been deleted.');
  });

  it('rejects an unauthenticated call', async () => {
    await expect(saveArtifactState({ id: artifactId, state: {} })).rejects.toThrow('Unauthorized');
  });
});

describe('updateArtifactMetadataFn (through the real server-fn RPC route)', () => {
  it('rejects a metadata update on a soft-deleted artifact', async () => {
    const { createArtifact, softDeleteArtifact } = await import('@/database/repository');
    const { db } = await import('@/database');

    const { artifact } = createArtifact(db, { title: 'To Be Deleted', type: 'spec', body: '{}' });

    softDeleteArtifact(db, artifact.id);

    await expect(
      updateArtifactMetadata(
        { id: artifact.id, title: 'New Title', description: null, tags: [] },
        { cookie: ownerCookie },
      ),
    ).rejects.toThrow('Artifact not found. It may have been deleted.');
  });
});
