/**
 * saveArtifactStateFn's handler body is written inline inside `.handler(...)` (see
 * artifacts.ts:22-32) and, unlike a plain function, can't be imported and called directly in a unit
 * test: calling the exported const outside the real server runtime throws "No Start context found
 * in AsyncLocalStorage" (see session-middleware.unit.test.ts's note) - the framework only executes
 * the real handler body when a request reaches it through TanStack Start's compiled server-fn RPC
 * route, which is generated by the `tanstackStart()` Vite plugin and isn't wired into
 * vitest.config.ts.
 *
 * This suite drives that real route for real via testing/server.ts, which boots Vite's own dev
 * server (the same request-handling stack `pnpm dev` runs) as an in-process test harness instead of
 * a spawned child process + TCP port - see that file's comment for exactly how, and for the
 * internal-API risk it accepts (a TanStack Start or Vite upgrade could break this loudly; that's
 * judged an acceptable trade for actually exercising saveArtifactStateFn's 64 KB cap and not-found
 * guard, the entire point of this file, rather than a test that can't fail when that logic breaks).
 */
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { bootTestServer, serverFnCaller, signInOwner } from '@testing/server';
import type { ServerFnCaller, TestServer } from '@testing/server';

const dbDir = mkdtempSync(join(tmpdir(), 'exhibit-artifacts-int-'));
const dbFile = join(dbDir, 'app.db');

process.env.DATABASE_PATH = dbFile;
/**
 * TanStack Start's compiled client stub reads this to build the RPC URL; the app itself never sets
 * it directly (Vite's `define` config normally inlines it at build time), so we own it here - see
 * test-server.ts.
 */
process.env.TSS_SERVER_FN_BASE = '/_serverFn/';

const ORIGIN = 'http://localhost:3000';
const OWNER_EMAIL = 'owner@example.com';
const OWNER_PASSWORD = 'correct horse battery staple';

let server: TestServer;
let artifactId: string;
let ownerCookie: string;
let saveArtifactState: ServerFnCaller;
let getArtifactDetail: ServerFnCaller;
let updateArtifactMetadata: ServerFnCaller;
let listArtifacts: ServerFnCaller;
let restoreArtifactFn: ServerFnCaller;
let revertArtifactVersion: ServerFnCaller;
let purgeArtifactFn: ServerFnCaller;

beforeAll(async () => {
  const { createArtifact } = await import('@/database/repository');
  const { db } = await import('@/database');
  const { seedOwner } = await import('@/lib/seed');

  await seedOwner(OWNER_EMAIL, OWNER_PASSWORD);

  const { artifact } = createArtifact(db, {
    title: 'Fixture',
    type: 'spec',
    body: JSON.stringify({
      root: 'a',
      elements: { a: { type: 'Prose', props: {}, children: [] } },
    }),
  });

  artifactId = artifact.id;

  server = await bootTestServer(new URL('../../vite.config.ts', import.meta.url));
  ownerCookie = await signInOwner(server, ORIGIN, OWNER_EMAIL, OWNER_PASSWORD);
  saveArtifactState = await serverFnCaller(
    server,
    '/src/lib/artifacts.ts',
    'saveArtifactStateFn',
    'POST',
    ORIGIN,
  );
  getArtifactDetail = await serverFnCaller(
    server,
    '/src/lib/artifacts.ts',
    'getArtifactDetailFn',
    'GET',
    ORIGIN,
  );
  updateArtifactMetadata = await serverFnCaller(
    server,
    '/src/lib/artifacts.ts',
    'updateArtifactMetadataFn',
    'POST',
    ORIGIN,
  );
  listArtifacts = await serverFnCaller(
    server,
    '/src/lib/artifacts.ts',
    'listArtifactsFn',
    'GET',
    ORIGIN,
  );
  restoreArtifactFn = await serverFnCaller(
    server,
    '/src/lib/artifacts.ts',
    'restoreArtifactFn',
    'POST',
    ORIGIN,
  );
  revertArtifactVersion = await serverFnCaller(
    server,
    '/src/lib/artifacts.ts',
    'revertArtifactVersionFn',
    'POST',
    ORIGIN,
  );
  purgeArtifactFn = await serverFnCaller(
    server,
    '/src/lib/artifacts.ts',
    'purgeArtifactFn',
    'POST',
    ORIGIN,
  );
}, 30000);

afterAll(async () => {
  await server.vite.close();
  rmSync(dbDir, { recursive: true, force: true });
});

describe('saveArtifactStateFn (through the real server-fn RPC route)', () => {
  it('persists state for a real, authenticated caller and it round-trips through getArtifactDetailFn', async () => {
    const saveResult = await saveArtifactState(
      { id: artifactId, state: { checked: true } },
      { cookie: ownerCookie },
    );

    expect(saveResult).toEqual({ saved: true });

    const detail = (await getArtifactDetail({ id: artifactId }, { cookie: ownerCookie })) as {
      state: unknown;
    };

    expect(detail.state).toEqual({ checked: true });
  });

  it('rejects a state payload over the 64 KB cap', async () => {
    await expect(
      saveArtifactState(
        { id: artifactId, state: { big: 'x'.repeat(70_000) } },
        { cookie: ownerCookie },
      ),
    ).rejects.toThrow('Interaction state exceeds the 64 KB limit.');
  });

  it('rejects an unknown artifact id', async () => {
    await expect(
      saveArtifactState({ id: 'nonexistent-id', state: {} }, { cookie: ownerCookie }),
    ).rejects.toThrow('Artifact not found. It may have been deleted.');
  });

  it('rejects an unauthenticated call', async () => {
    await expect(saveArtifactState({ id: artifactId, state: {} })).rejects.toThrow('Unauthorized');
  });
});

describe('updateArtifactMetadataFn (through the real server-fn RPC route)', () => {
  it('rejects a metadata update on a soft-deleted artifact', async () => {
    const { createArtifact, softDeleteArtifact } = await import('@/database/repository');
    const { db } = await import('@/database');

    const { artifact } = createArtifact(db, { title: 'To Be Deleted', type: 'spec', body: '{}' });

    softDeleteArtifact(db, artifact.id);

    await expect(
      updateArtifactMetadata(
        { id: artifact.id, title: 'New Title', description: null, tags: [] },
        { cookie: ownerCookie },
      ),
    ).rejects.toThrow('Artifact not found. It may have been deleted.');
  });
});

describe('revertArtifactVersionFn (through the real server-fn RPC route)', () => {
  it('appends an older version body as the new latest version', async () => {
    const { appendVersion, createArtifact } = await import('@/database/repository');
    const { db } = await import('@/database');

    const { artifact } = createArtifact(db, { title: 'Revised', type: 'markdown', body: '# v1' });

    appendVersion(db, artifact.id, '# v2');

    const restored = (await revertArtifactVersion(
      { id: artifact.id, version: 1 },
      { cookie: ownerCookie },
    )) as { version: number; body: string };

    expect(restored).toMatchObject({ version: 3, body: '# v1' });

    const detail = (await getArtifactDetail({ id: artifact.id }, { cookie: ownerCookie })) as {
      version: { version: number; body: string };
      versions: { version: number }[];
    };

    expect(detail.version).toMatchObject({ version: 3, body: '# v1' });
    expect(detail.versions.map((v) => v.version)).toEqual([1, 2, 3]);
  });

  it('rejects a version the artifact does not have', async () => {
    const { createArtifact } = await import('@/database/repository');
    const { db } = await import('@/database');

    const { artifact } = createArtifact(db, { title: 'Single', type: 'markdown', body: '# v1' });

    await expect(
      revertArtifactVersion({ id: artifact.id, version: 9 }, { cookie: ownerCookie }),
    ).rejects.toThrow('Artifact not found. It may have been deleted.');
  });

  it('rejects an unauthenticated call', async () => {
    await expect(revertArtifactVersion({ id: artifactId, version: 1 })).rejects.toThrow(
      'Unauthorized',
    );
  });
});

describe('restoreArtifactFn / purgeArtifactFn (through the real server-fn RPC route)', () => {
  async function createDeleted(title: string) {
    const { createArtifact, softDeleteArtifact } = await import('@/database/repository');
    const { db } = await import('@/database');

    const { artifact } = createArtifact(db, { title, type: 'spec', body: '{}' });

    softDeleteArtifact(db, artifact.id);

    return artifact.id;
  }

  it('lists a soft-deleted artifact under deleted: true and restores it back to the live list', async () => {
    const id = await createDeleted('Trashed');

    const trashed = (await listArtifacts({ deleted: true }, { cookie: ownerCookie })) as {
      items: { id: string }[];
    };

    expect(trashed.items.map((item) => item.id)).toContain(id);

    const restored = (await restoreArtifactFn({ id }, { cookie: ownerCookie })) as {
      deletedAt: number | null;
    };

    expect(restored.deletedAt).toBeNull();

    const live = (await listArtifacts({}, { cookie: ownerCookie })) as { items: { id: string }[] };

    expect(live.items.map((item) => item.id)).toContain(id);
  });

  it('rejects a restore of an unknown artifact id', async () => {
    await expect(
      restoreArtifactFn({ id: 'nonexistent-id' }, { cookie: ownerCookie }),
    ).rejects.toThrow('Artifact not found. It may have been deleted.');
  });

  it('purges an artifact and reports false when there is nothing left to purge', async () => {
    const id = await createDeleted('Purged');

    expect(await purgeArtifactFn({ id }, { cookie: ownerCookie })).toEqual({ purged: true });
    expect(await purgeArtifactFn({ id }, { cookie: ownerCookie })).toEqual({ purged: false });

    await expect(restoreArtifactFn({ id }, { cookie: ownerCookie })).rejects.toThrow(
      'Artifact not found. It may have been deleted.',
    );
  });

  it('rejects unauthenticated restore and purge calls', async () => {
    const id = await createDeleted('Guarded');

    await expect(restoreArtifactFn({ id })).rejects.toThrow('Unauthorized');
    await expect(purgeArtifactFn({ id })).rejects.toThrow('Unauthorized');
  });
});
