import { layers, namedFlavor, type Flavor } from '@protomaps/basemaps';
import type MapLibreGL from 'maplibre-gl';

import type { Theme } from '@/components/ui/map/map-context';

/*
 * House basemap: Protomaps tiles drawn in the app's palette. Each flavor spreads the package's
 * monochrome base (black/white) and re-maps the visible slots onto the gray ladder from
 * styles.css. MapLibre's color parser predates oklch, so the ladders below are baked sRGB hex
 * conversions of the tokens they name — re-derive them if the ladder in styles.css changes.
 */

/** Cool-charcoal dark ladder (--gray-1..11) plus the map-only landcover tints. */
const dark = {
  gray1: '#131518',
  gray2: '#1a1c1f',
  gray3: '#212326',
  gray4: '#282a2d',
  gray5: '#303234',
  gray6: '#393b3d',
  gray8: '#5d5e5f',
  gray9: '#747474',
  gray10: '#9e9e9e',
  gray11: '#cacaca',
  water: '#0a0f14', // recessed below the page floor, keeps the hue-255 cast
  park: '#151f17',
  wood: '#131c15',
  scrub: '#141d16',
  sand: '#1f1b16',
  glacier: '#1f2123',
  paved: '#1d1f22', // pedestrian ways + tunnel fills, between gray-2 and gray-3
};

const darkFlavor: Flavor = {
  ...namedFlavor('black'),
  background: dark.gray1, // matches the page background
  earth: dark.gray2, // land sits slightly raised, like a surface
  water: dark.water,
  buildings: dark.gray3,
  pier: dark.gray3,
  park_a: dark.park,
  park_b: dark.park,
  wood_a: dark.wood,
  wood_b: dark.wood,
  scrub_a: dark.scrub,
  scrub_b: dark.scrub,
  zoo: dark.park,
  glacier: dark.glacier,
  sand: dark.sand,
  beach: dark.sand,
  aerodrome: dark.gray2,
  runway: dark.gray5,
  pedestrian: dark.paved,
  hospital: dark.gray3,
  industrial: dark.gray2,
  school: dark.gray2,
  military: dark.gray2,
  // roads climb the ladder with importance; casings sink back to earth
  other: dark.gray3,
  minor_service: dark.gray3,
  minor_b: dark.gray3,
  minor_a: dark.gray4,
  link: dark.gray4,
  major: dark.gray5,
  highway: dark.gray6,
  railway: dark.gray4,
  minor_service_casing: dark.gray2,
  minor_casing: dark.gray2,
  link_casing: dark.gray2,
  major_casing_early: dark.gray2,
  major_casing_late: dark.gray2,
  highway_casing_early: dark.gray2,
  highway_casing_late: dark.gray2,
  tunnel_other: dark.paved,
  tunnel_minor: dark.paved,
  tunnel_link: dark.paved,
  tunnel_major: dark.paved,
  tunnel_highway: dark.paved,
  tunnel_other_casing: dark.gray1,
  tunnel_minor_casing: dark.gray1,
  tunnel_link_casing: dark.gray1,
  tunnel_major_casing: dark.gray1,
  tunnel_highway_casing: dark.gray1,
  bridges_other: dark.gray3,
  bridges_minor: dark.gray3,
  bridges_link: dark.gray4,
  bridges_major: dark.gray5,
  bridges_highway: dark.gray6,
  bridges_other_casing: dark.gray2,
  bridges_minor_casing: dark.gray2,
  bridges_link_casing: dark.gray2,
  bridges_major_casing: dark.gray2,
  bridges_highway_casing: dark.gray2,
  boundaries: dark.gray8,
  city_label: dark.gray11,
  city_label_halo: dark.gray1,
  country_label: dark.gray10,
  state_label: dark.gray9,
  state_label_halo: dark.gray1,
  subplace_label: dark.gray10,
  subplace_label_halo: dark.gray1,
  ocean_label: dark.gray8,
  roads_label_major: dark.gray10,
  roads_label_major_halo: dark.gray2,
  roads_label_minor: dark.gray9,
  roads_label_minor_halo: dark.gray2,
  address_label: dark.gray8,
  address_label_halo: dark.gray2,
};

/** Light ladder (--gray-1..11) plus the map-only landcover tints. */
const light = {
  gray1: '#ffffff',
  gray2: '#f8f8f8',
  gray3: '#f2f2f2',
  gray4: '#ebebeb',
  gray5: '#e4e4e4',
  gray6: '#dedede',
  gray8: '#a0a0a0',
  gray9: '#868686',
  gray10: '#747474',
  gray11: '#383838',
  water: '#d3e0ea',
  park: '#e1f2e5',
  wood: '#dbeedf',
  scrub: '#deefe2',
  sand: '#f6efe1',
  glacier: '#f2f6f9',
};

const lightFlavor: Flavor = {
  ...namedFlavor('white'),
  background: light.gray1,
  earth: light.gray2,
  water: light.water,
  buildings: light.gray4,
  pier: light.gray4,
  park_a: light.park,
  park_b: light.park,
  wood_a: light.wood,
  wood_b: light.wood,
  scrub_a: light.scrub,
  scrub_b: light.scrub,
  zoo: light.park,
  glacier: light.glacier,
  sand: light.sand,
  beach: light.sand,
  aerodrome: light.gray3,
  runway: light.gray6,
  pedestrian: light.gray3,
  hospital: light.gray3,
  industrial: light.gray3,
  school: light.gray3,
  military: light.gray4,
  // light maps invert the road logic: white fills, ladder casings
  other: light.gray1,
  minor_service: light.gray1,
  minor_b: light.gray1,
  minor_a: light.gray1,
  link: light.gray1,
  major: light.gray1,
  highway: light.gray1,
  railway: light.gray5,
  minor_service_casing: light.gray4,
  minor_casing: light.gray5,
  link_casing: light.gray5,
  major_casing_early: light.gray5,
  major_casing_late: light.gray5,
  highway_casing_early: light.gray6,
  highway_casing_late: light.gray6,
  tunnel_other: light.gray3,
  tunnel_minor: light.gray3,
  tunnel_link: light.gray3,
  tunnel_major: light.gray3,
  tunnel_highway: light.gray3,
  tunnel_other_casing: light.gray4,
  tunnel_minor_casing: light.gray4,
  tunnel_link_casing: light.gray4,
  tunnel_major_casing: light.gray4,
  tunnel_highway_casing: light.gray4,
  bridges_other: light.gray1,
  bridges_minor: light.gray1,
  bridges_link: light.gray1,
  bridges_major: light.gray1,
  bridges_highway: light.gray1,
  bridges_other_casing: light.gray5,
  bridges_minor_casing: light.gray5,
  bridges_link_casing: light.gray5,
  bridges_major_casing: light.gray5,
  bridges_highway_casing: light.gray6,
  boundaries: light.gray8,
  city_label: light.gray11,
  city_label_halo: light.gray1,
  country_label: light.gray10,
  state_label: light.gray9,
  state_label_halo: light.gray1,
  subplace_label: light.gray10,
  subplace_label_halo: light.gray1,
  ocean_label: light.gray9,
  roads_label_major: light.gray9,
  roads_label_major_halo: light.gray1,
  roads_label_minor: light.gray8,
  roads_label_minor_halo: light.gray1,
  address_label: light.gray8,
  address_label_halo: light.gray1,
};

const flavors: Record<Theme, { flavor: Flavor; sprite: string }> = {
  dark: { flavor: darkFlavor, sprite: 'black' },
  light: { flavor: lightFlavor, sprite: 'white' },
};

export function buildProtomapsStyle(theme: Theme, apiKey: string): MapLibreGL.StyleSpecification {
  const { flavor, sprite } = flavors[theme];

  return {
    version: 8,
    glyphs: 'https://protomaps.github.io/basemaps-assets/fonts/{fontstack}/{range}.pbf',
    sprite: `https://protomaps.github.io/basemaps-assets/sprites/v4/${sprite}`,
    sources: {
      protomaps: {
        type: 'vector',
        url: `https://api.protomaps.com/tiles/v4.json?key=${apiKey}`,
        attribution:
          '<a href="https://protomaps.com">Protomaps</a> © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
      },
    },
    layers: layers('protomaps', flavor, { lang: 'en' }),
  };
}
