/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedDocsRouteImport } from './routes/_authed/docs'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known/openid-configuration'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as RenderIdNRouteImport } from './routes/render.$id.$n'
import { Route as DownloadIdNRouteImport } from './routes/download.$id.$n'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedDevLibraryRouteImport } from './routes/_authed/dev.library'
import { Route as AuthedDevLibraryIndexRouteImport } from './routes/_authed/dev.library/index'
import { Route as AuthedAIdIndexRouteImport } from './routes/_authed/a.$id/index'
import { Route as AuthedDevLibrarySlugRouteImport } from './routes/_authed/dev.library/$slug'
import { Route as AuthedAIdVNRouteImport } from './routes/_authed/a.$id/v.$n'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocsRoute = AuthedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthedRoute,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const RenderIdNRoute = RenderIdNRouteImport.update({
  id: '/render/$id/$n',
  path: '/render/$id/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIdNRoute = DownloadIdNRouteImport.update({
  id: '/download/$id/$n',
  path: '/download/$id/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDevLibraryRoute = AuthedDevLibraryRouteImport.update({
  id: '/dev/library',
  path: '/dev/library',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevLibraryIndexRoute = AuthedDevLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDevLibraryRoute,
} as any)
const AuthedAIdIndexRoute = AuthedAIdIndexRouteImport.update({
  id: '/a/$id/',
  path: '/a/$id/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevLibrarySlugRoute = AuthedDevLibrarySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthedDevLibraryRoute,
} as any)
const AuthedAIdVNRoute = AuthedAIdVNRouteImport.update({
  id: '/a/$id/v/$n',
  path: '/a/$id/v/$n',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/consent': typeof ConsentRoute
  '/healthz': typeof HealthzRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/docs': typeof AuthedDocsRoute
  '/settings': typeof AuthedSettingsRoute
  '/dev/library': typeof AuthedDevLibraryRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/download/$id/$n': typeof DownloadIdNRoute
  '/render/$id/$n': typeof RenderIdNRoute
  '/dev/library/$slug': typeof AuthedDevLibrarySlugRoute
  '/a/$id/': typeof AuthedAIdIndexRoute
  '/dev/library/': typeof AuthedDevLibraryIndexRoute
  '/a/$id/v/$n': typeof AuthedAIdVNRoute
}
export interface FileRoutesByTo {
  '/consent': typeof ConsentRoute
  '/healthz': typeof HealthzRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/docs': typeof AuthedDocsRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/download/$id/$n': typeof DownloadIdNRoute
  '/render/$id/$n': typeof RenderIdNRoute
  '/dev/library/$slug': typeof AuthedDevLibrarySlugRoute
  '/a/$id': typeof AuthedAIdIndexRoute
  '/dev/library': typeof AuthedDevLibraryIndexRoute
  '/a/$id/v/$n': typeof AuthedAIdVNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/consent': typeof ConsentRoute
  '/healthz': typeof HealthzRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/_authed/docs': typeof AuthedDocsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/dev/library': typeof AuthedDevLibraryRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/download/$id/$n': typeof DownloadIdNRoute
  '/render/$id/$n': typeof RenderIdNRoute
  '/_authed/dev/library/$slug': typeof AuthedDevLibrarySlugRoute
  '/_authed/a/$id/': typeof AuthedAIdIndexRoute
  '/_authed/dev/library/': typeof AuthedDevLibraryIndexRoute
  '/_authed/a/$id/v/$n': typeof AuthedAIdVNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/healthz'
    | '/mcp'
    | '/reset-password'
    | '/sign-in'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/docs'
    | '/settings'
    | '/dev/library'
    | '/api/auth/$'
    | '/download/$id/$n'
    | '/render/$id/$n'
    | '/dev/library/$slug'
    | '/a/$id/'
    | '/dev/library/'
    | '/a/$id/v/$n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/consent'
    | '/healthz'
    | '/mcp'
    | '/reset-password'
    | '/sign-in'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/docs'
    | '/settings'
    | '/'
    | '/api/auth/$'
    | '/download/$id/$n'
    | '/render/$id/$n'
    | '/dev/library/$slug'
    | '/a/$id'
    | '/dev/library'
    | '/a/$id/v/$n'
  id:
    | '__root__'
    | '/_authed'
    | '/consent'
    | '/healthz'
    | '/mcp'
    | '/reset-password'
    | '/sign-in'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/_authed/docs'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/dev/library'
    | '/api/auth/$'
    | '/download/$id/$n'
    | '/render/$id/$n'
    | '/_authed/dev/library/$slug'
    | '/_authed/a/$id/'
    | '/_authed/dev/library/'
    | '/_authed/a/$id/v/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  HealthzRoute: typeof HealthzRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DownloadIdNRoute: typeof DownloadIdNRoute
  RenderIdNRoute: typeof RenderIdNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/docs': {
      id: '/_authed/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthedDocsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render/$id/$n': {
      id: '/render/$id/$n'
      path: '/render/$id/$n'
      fullPath: '/render/$id/$n'
      preLoaderRoute: typeof RenderIdNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$id/$n': {
      id: '/download/$id/$n'
      path: '/download/$id/$n'
      fullPath: '/download/$id/$n'
      preLoaderRoute: typeof DownloadIdNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dev/library': {
      id: '/_authed/dev/library'
      path: '/dev/library'
      fullPath: '/dev/library'
      preLoaderRoute: typeof AuthedDevLibraryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dev/library/': {
      id: '/_authed/dev/library/'
      path: '/'
      fullPath: '/dev/library/'
      preLoaderRoute: typeof AuthedDevLibraryIndexRouteImport
      parentRoute: typeof AuthedDevLibraryRoute
    }
    '/_authed/a/$id/': {
      id: '/_authed/a/$id/'
      path: '/a/$id'
      fullPath: '/a/$id/'
      preLoaderRoute: typeof AuthedAIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dev/library/$slug': {
      id: '/_authed/dev/library/$slug'
      path: '/$slug'
      fullPath: '/dev/library/$slug'
      preLoaderRoute: typeof AuthedDevLibrarySlugRouteImport
      parentRoute: typeof AuthedDevLibraryRoute
    }
    '/_authed/a/$id/v/$n': {
      id: '/_authed/a/$id/v/$n'
      path: '/a/$id/v/$n'
      fullPath: '/a/$id/v/$n'
      preLoaderRoute: typeof AuthedAIdVNRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedDevLibraryRouteChildren {
  AuthedDevLibrarySlugRoute: typeof AuthedDevLibrarySlugRoute
  AuthedDevLibraryIndexRoute: typeof AuthedDevLibraryIndexRoute
}

const AuthedDevLibraryRouteChildren: AuthedDevLibraryRouteChildren = {
  AuthedDevLibrarySlugRoute: AuthedDevLibrarySlugRoute,
  AuthedDevLibraryIndexRoute: AuthedDevLibraryIndexRoute,
}

const AuthedDevLibraryRouteWithChildren =
  AuthedDevLibraryRoute._addFileChildren(AuthedDevLibraryRouteChildren)

interface AuthedRouteChildren {
  AuthedDocsRoute: typeof AuthedDocsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedDevLibraryRoute: typeof AuthedDevLibraryRouteWithChildren
  AuthedAIdIndexRoute: typeof AuthedAIdIndexRoute
  AuthedAIdVNRoute: typeof AuthedAIdVNRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDocsRoute: AuthedDocsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedDevLibraryRoute: AuthedDevLibraryRouteWithChildren,
  AuthedAIdIndexRoute: AuthedAIdIndexRoute,
  AuthedAIdVNRoute: AuthedAIdVNRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ConsentRoute: ConsentRoute,
  HealthzRoute: HealthzRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DownloadIdNRoute: DownloadIdNRoute,
  RenderIdNRoute: RenderIdNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
